=== terraframe/Runway-SDK/runwaysdk-gis/runwaysdk-gis-test/src/main/resources/instance.xsd
<?xml version="1.0"?>
<!--

    Copyright (c) 2015 TerraFrame, Inc. All rights reserved.

    This file is part of Runway SDK GIS(tm).

    Runway SDK GIS(tm) is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    Runway SDK GIS(tm) is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with Runway SDK GIS(tm).  If not, see <http://www.gnu.org/licenses/>.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--The root element of the xml schema-->
  <xs:element name="Instances">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="object"/>
        <xs:element ref="relationship"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

    <!--A particualr instance of a class dataObject-->
  <xs:element name="object">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <!--The attribute-value pairings of the instance-->
        <xs:element ref="value"/>
        <!--The attribute-multi xml oid pairing of the instance-->
        <xs:element ref="enumeration"/>
        <!--The struct attribute values-->
        <xs:element ref="struct"/>
      </xs:choice>
      <!--A unqiue oid for the instance-->
      <xs:attribute name="oid" type="xs:string" use="required"/>
      <!--The qualified path of the class being instaniated-->
      <xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <!--A particular instance of a Relationship object. A relationship cannot reference a standalone type-->
  <xs:element name="relationship">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <!--The attribute-value pairings of the instance-->
        <xs:element ref="value"/>
        <!--The attribute-multi xml oid pairing of the instance-->
        <xs:element ref="enumeration"/>
        <!--The struct attribute values-->
        <xs:element ref="struct"/>
      </xs:choice>
      <!--A unqiue oid for the instance-->
      <xs:attribute name="oid" type="xs:string" use="required"/>
      <!--The qualified path of the class being instaniated-->
      <xs:attribute name="type" type="xs:string" use="required"/>
      <!--parentOid: The xml oid of the instance of the parent-->
      <xs:attribute name="parentOid" type="xs:string" use="required"/>
      <!--childOid: The xml oid of the instance of the child-->
      <xs:attribute name="childOid" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <!--Sets the value of an attribute for a particular instance-->
  <xs:element name="value">
    <xs:complexType>
      <xs:simpleContent>
        <!--value: The value for the attribute instantiated-->
        <xs:extension base="xs:string">
          <!--attribute: The name of the attribute instantiated-->
          <xs:attribute name="attribute" type="xs:string" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <!--Sets the value of an attribute which references multiple instances-->
  <xs:element name="enumeration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="value" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <!--oid: The xml oid of the class being referenced-->
            <xs:attribute name="value" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <!--attribute: The name of attribute being instantiated-->
      <xs:attribute name="attribute" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <!--Use for instance of struct attributes, must reference standalone type-->
  <xs:element name="struct">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <!--The attribute-value pairings of the instance-->
        <xs:element ref="value"/>
        <!--The attribute-multi xml oid pairing of the instance-->
        <xs:element ref="enumeration"/>
      </xs:choice>
      <!--attribute: The name of the struct attribute-->
      <xs:attribute name="attribute" type="xs:string" use="required"/>
      <!--attribute: The oid of the struct object-->
      <xs:attribute name="oid" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== terraframe/Runway-SDK/runwaysdk-test/src/main/XMLFiles/testSequence.xml
<!--

    Copyright (c) 2022 TerraFrame, Inc. All rights reserved.

    This file is part of Runway SDK(tm).

    Runway SDK(tm) is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    Runway SDK(tm) is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with Runway SDK(tm).  If not, see <http://www.gnu.org/licenses/>.

-->
<Instances xsi:noNamespaceSchemaLocation="trunk/scripts/metadata/instance.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <object type="com.runwaysdk.system.metadata.MdBusiness" id="r52y0byilihbnhcf1qsx9paxkgwektdc00000000000000000000000000000001">
    <struct attribute="displayLabel" id="NM200904230000000000000000000001NM200904120000000000000000000030">
      <value attribute="keyName">
        <![CDATA[NM200904230000000000000000000001NM200904120000000000000000000030]]>
      </value>
      <value attribute="siteMaster">
        <![CDATA[www.runwaysdk.com]]>
      </value>
      <value attribute="defaultLocale">
        <![CDATA[Class1]]>
      </value>
    </struct>
    <value attribute="owner">
      <![CDATA[0000000000000000000000000000001000000000000000000000000000000003]]>
    </value>
    <selection attribute="cacheAlgorithm">
      <value value="0000000000000000000000000000023100000000000000000000000000000222" />
    </selection>
    <value attribute="createDate">
      <![CDATA[2008-02-14 20:40:44]]>
    </value>
    <value attribute="baseSource">
      <![CDATA[package test.xmlclasses;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to Class1.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class Class1Base extends com.runwaysdk.business.Business implements com.runwaysdk.generation.loader.Reloadable
{
  public final static String CLASS = "test.xmlclasses.Class1";
  public Class1Base()
  {
    super();
  }

  public String getKeyName()
  {
    return getValue("keyName");
  }

  public void validateKeyName()
  {
    this.validateAttribute("keyName");
  }

  public void setKeyName(String value)
  {
    if(value == null)
    {
      setValue("keyName", "");
    }
    else
    {
      setValue("keyName", value);
    }
  }

  public String getTestCharacter()
  {
    return getValue("testCharacter");
  }

  public void validateTestCharacter()
  {
    this.validateAttribute("testCharacter");
  }

  public void setTestCharacter(String value)
  {
    if(value == null)
    {
      setValue("testCharacter", "");
    }
    else
    {
      setValue("testCharacter", value);
    }
  }

  protected String getDeclaredType()
  {
    return "test.xmlclasses.Class1";
  }

  public static test.xmlclasses.Class1 lock(java.lang.String id)
  {
    Class1 _instance = Class1.get(id);
    _instance.lock();

    return _instance;
  }

  public static test.xmlclasses.Class1 unlock(java.lang.String id)
  {
    Class1 _instance = Class1.get(id);
    _instance.unlock();

    return _instance;
  }

  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
]]>
    </value>
    <value attribute="keyName">
      <![CDATA[test.xmlclasses.Class1]]>
    </value>
    <value attribute="siteMaster">
      <![CDATA[www.notrunwaysdk.com]]>
    </value>
    <value attribute="lastUpdatedBy">
      <![CDATA[0000000000000000000000000000001000000000000000000000000000000003]]>
    </value>
    <value attribute="dtoSource">
      <![CDATA[package test.xmlclasses;

public abstract class Class1DTOBase extends com.runwaysdk.transport.BusinessDTO implements com.runwaysdk.generation.loader.Reloadable
{
  public final static String CLASS = "test.xmlclasses.Class1";
  private static final long serialVersionUID = 1203046856505L;

  protected Class1DTOBase(com.runwaysdk.constants.ProxyIF proxy)
  {
    super(proxy);
  }

  /**
  * Copy Constructor: Duplicates the values and attributes of the given BusinessDTO into a new DTO.
  *
  * @param businessDTO The BusinessDTO to duplicate
  * @param proxy The proxy this DTO should use to communicate with the server.
  */
  protected Class1DTOBase(com.runwaysdk.transport.BusinessDTO businessDTO, com.runwaysdk.constants.ProxyIF proxy)
  {
    super(businessDTO, proxy);
  }

  protected java.lang.String getDeclaredType()
  {
    return "test.xmlclasses.Class1";
  }

  public String getSiteMaster()
  {
    return getValue("siteMaster");
  }

  public boolean isSiteMasterWritable()
  {
    return isWritable("siteMaster");
  }

  public boolean isSiteMasterReadable()
  {
    return isReadable("siteMaster");
  }

  public boolean isSiteMasterModified()
  {
    return isModified("siteMaster");
  }

  public com.runwaysdk.transport.metadata.AttributeMdDTO siteMaster()
  {
    return (com.runwaysdk.transport.metadata.AttributeMdDTO) getAttributeDTO("siteMaster").getAttributeMdDTO();
  }

  public String getKeyName()
  {
    return getValue("keyName");
  }

  public void setKeyName(String value)
  {
    setValue("keyName", value);
  }

  public boolean isKeyNameWritable()
  {
    return isWritable("keyName");
  }

  public boolean isKeyNameReadable()
  {
    return isReadable("keyName");
  }

  public boolean isKeyNameModified()
  {
    return isModified("keyName");
  }

  public com.runwaysdk.transport.metadata.AttributeMdDTO keyName()
  {
    return (com.runwaysdk.transport.metadata.AttributeMdDTO) getAttributeDTO("keyName").getAttributeMdDTO();
  }

  public com.runwaysdk.system.SingleActorDTO getCreatedBy()
  {
    return com.runwaysdk.system.SingleActorDTO.get(getProxy(), getValue("createdBy"));
  }

  public boolean isCreatedByWritable()
  {
    return isWritable("createdBy");
  }

  public boolean isCreatedByReadable()
  {
    return isReadable("createdBy");
  }

  public boolean isCreatedByModified()
  {
    return isModified("createdBy");
  }

  public com.runwaysdk.transport.metadata.AttributeMdDTO createdBy()
  {
    return (com.runwaysdk.transport.metadata.AttributeMdDTO) getAttributeDTO("createdBy").getAttributeMdDTO();
  }

  public java.util.Date getCreateDate()
  {
    return com.runwaysdk.constants.MdAttributeDateTimeUtil.getTypeSafeValue(getValue("createDate"));
  }

  public boolean isCreateDateWritable()
  {
    return isWritable("createDate");
  }

  public boolean isCreateDateReadable()
  {
    return isReadable("createDate");
  }

  public boolean isCreateDateModified()
  {
    return isModified("createDate");
  }

  public com.runwaysdk.transport.metadata.AttributeMdDTO createDate()
  {
    return (com.runwaysdk.transport.metadata.AttributeMdDTO) getAttributeDTO("createDate").getAttributeMdDTO();
  }

  public com.runwaysdk.system.SingleActorDTO getLastUpdatedBy()
  {
    return com.runwaysdk.system.SingleActorDTO.get(getProxy(), getValue("lastUpdatedBy"));
  }

  public boolean isLastUpdatedByWritable()
  {
    return isWritable("lastUpdatedBy");
  }

  public boolean isLastUpdatedByReadable()
  {
    return isReadable("lastUpdatedBy");
  }

  public boolean isLastUpdatedByModified()
  {
    return isModified("lastUpdatedBy");
  }

  public com.runwaysdk.transport.metadata.AttributeMdDTO lastUpdatedBy()
  {
    return (com.runwaysdk.transport.metadata.AttributeMdDTO) getAttributeDTO("lastUpdatedBy").getAttributeMdDTO();
  }

  public java.util.Date getLastUpdateDate()
  {
    return com.runwaysdk.constants.MdAttributeDateTimeUtil.getTypeSafeValue(getValue("lastUpdateDate"));
  }

  public boolean isLastUpdateDateWritable()
  {
    return isWritable("lastUpdateDate");
  }

  public boolean isLastUpdateDateReadable()
  {
    return isReadable("lastUpdateDate");
  }

  public boolean isLastUpdateDateModified()
  {
    return isModified("lastUpdateDate");
  }

  public com.runwaysdk.transport.metadata.AttributeMdDTO lastUpdateDate()
  {
    return (com.runwaysdk.transport.metadata.AttributeMdDTO) getAttributeDTO("lastUpdateDate").getAttributeMdDTO();
  }

  public com.runwaysdk.system.UsersDTO getLockedBy()
  {
    return com.runwaysdk.system.UsersDTO.get(getProxy(), getValue("lockedBy"));
  }

  public boolean isLockedByWritable()
  {
    return isWritable("lockedBy");
  }

  public boolean isLockedByReadable()
  {
    return isReadable("lockedBy");
  }

  public boolean isLockedByModified()
  {
    return isModified("lockedBy");
  }

  public com.runwaysdk.transport.metadata.AttributeMdDTO lockedBy()
  {
    return (com.runwaysdk.transport.metadata.AttributeMdDTO) getAttributeDTO("lockedBy").getAttributeMdDTO();
  }

  public Long getSeq()
  {
    return com.runwaysdk.constants.MdAttributeLongUtil.getTypeSafeValue(getValue("seq"));
  }

  public boolean isSeqWritable()
  {
    return isWritable("seq");
  }

  public boolean isSeqReadable()
  {
    return isReadable("seq");
  }

  public boolean isSeqModified()
  {
    return isModified("seq");
  }

  public com.runwaysdk.transport.metadata.AttributeNumberMdDTO seq()
  {
    return (com.runwaysdk.transport.metadata.AttributeNumberMdDTO) getAttributeDTO("seq").getAttributeMdDTO();
  }

  public com.runwaysdk.system.ActorDTO getOwner()
  {
    return com.runwaysdk.system.ActorDTO.get(getProxy(), getValue("owner"));
  }

  public boolean isOwnerWritable()
  {
    return isWritable("owner");
  }

  public boolean isOwnerReadable()
  {
    return isReadable("owner");
  }

  public boolean isOwnerModified()
  {
    return isModified("owner");
  }

  public com.runwaysdk.transport.metadata.AttributeMdDTO owner()
  {
